version: '3.8'
services:
  db:
    container_name: recruit-management-db
    image: postgres:14.0-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recruit-management
      - POSTGRES_PASSWORD=nagato8
    tty: true
  api:
    container_name: recruit-management-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - './api/:/app/'
    ports:
      - "8080:8080"
    tty: true
volumes:
  pgdata: